version: '3.8'

services:
  # PostgreSQL DB
  postgres:
    image: postgres
    container_name: whatisthis-postgres
    environment:
      POSTGRES_USER: whatisthis
      POSTGRES_PASSWORD: whatisthis
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: whatisthis-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: whatisthis
      RABBITMQ_DEFAULT_PASS: whatisthis
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - microservices-network

  # Proxy Server
  nginx:
    image: nginx:latest
    container_name: whatisthis-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - microservices-network
    depends_on:
      - authentication
      - scorer

  # Authentication Service
  authentication:
    build:
      context: ./authentication
    image: whatisthis-authentication
    container_name: whatisthis-authentication
    ports:
      # Exposing gRPC for now because nginx refuses to work
      - '50050:50050'
    depends_on:
      - postgres
    networks:
      - microservices-network

  # Scorer Service
  scorer:
    build:
      context: ./scorer
    image: whatisthis-scorer
    container_name: whatisthis-scorer
    depends_on:
      - postgres
      - rabbitmq
      - authentication
    env_file:
      - ./scorer/.env
    networks:
      - microservices-network

# Network Configuration
networks:
  microservices-network:
    driver: bridge
