version: '3.8'

services:
  postgresql:
    image: postgres
    container_name: whatisthis
    environment:
      POSTGRES_USER: whatisthis
      POSTGRES_PASSWORD: whatisthis
      POSTGRES_DB: authentication
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
